project:
  type: website
  output-dir: docs

website:
  title: "Basic Fundamentals of R"
  navbar:
    background: dark
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Content
        menu: 
          - href: Documentation.qmd
            text: Documentation
          - href: Videos.qmd
            text: Videos
      - text: Course
        menu:
          - href: fundament_programation.qmd
            text: ¿What's the programming logical? 
          - href: basic1.qmd
            text: What's R?
          - href: basic0.qmd
            text: Fundaments in R
          - href: basic2.qmd
            text: Data organization and tables
          - href: basic3.qmd
            text: Manage & import data
          - href: basic4.qmd
            text: Ggplot2 & data representation
          - href: basic5.qmd
            text: Statistical Analysis  Introduction With R
      - href: References.qmd
        text: References
          
    right: 
      - icon: twitter
        href: https://x.com/clementegarcC
      - icon: linkedin
        href: https://www.linkedin.com/in/xavier-clemente-garc%C3%ADa-cevallos-b4727a206/
      - icon: github
        href: https://github.com/xavierclementegarcia
      - text: '<img src="https://investigacion.udca.edu.co/wp-content/uploads/2018/04/cvlac.svg" alt="CLVAC" style="width: 20px; height: 20px;">'
        href: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0002018236
      - text: '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/ORCID_iD.svg/1024px-ORCID_iD.svg.png" alt="ORCID" style="width: 20px; height: 20px;">'
        href: https://orcid.org/0000-0002-3284-2363

  page-footer:
    left: |
      Xavier Clemente García Cevallos. All content licensed under <i class="fab fa-creative-commons"></i> 
      <i class="fab fa-creative-commons-by"></i>  The content used is for educational purposes only.

    center: 
      - icon: twitter
        href: https://x.com/clementegarcC
      - icon: linkedin
        href: https://www.linkedin.com/in/xavier-clemente-garc%C3%ADa-cevallos-b4727a206/
      - icon: github
        href: https://github.com/xavierclementegarcia
      - text: '<img src="https://investigacion.udca.edu.co/wp-content/uploads/2018/04/cvlac.svg" alt="CLVAC" style="width: 20px; height: 20px;">'
        href: https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0002018236
      - text: '<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/ORCID_iD.svg/1024px-ORCID_iD.svg.png" alt="ORCID" style="width: 20px; height: 20px;">'
        href: https://orcid.org/0000-0002-3284-2363
    right: |
      Made with <a href="https://www.r-project.org/"><img src="https://www.r-project.org/Rlogo.png" alt="R" width="25px"></a> 
      and <a href="https://quarto.org/"><img src="https://quarto.org/quarto.png" alt="Quarto" width="65px"></a>.

format:
  html:
    include-in-header: fontawesome.html
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
