---
title: "Basic Fundamentals of R"
theme:
  light: flatly
  dark: darkly
---

Hola!

Bienvenido

Este curso inicialmente estará hecho en español, mi lenguaje natal. La idea es que pueda ser una forma más sencilla de explicar R, sin tanto texto y sin demasiadas horas.

Aquí podrás encontrar a toda hora y en cualquier momento pequeños ejemplos explicativos que pueden ayudarte en tu camino dentro de las Ciencias Biológicas con R. Buena suerte.

En el apartado de "Course" encontrará toda la información resumida en 6 diapositivas para que puedas aplicar el tidyverse, gráficos, tablas, pruebas estadísticas comunes en Biología y además en un futuro un material para usar R Markdown.

## Contenido del curso {.scrollable}

**Puedes acceder al contenido del curso en el apartado curso del menú**

-   Introducción a R
-   Tipos, estructuras y operadores de datos
-   Tablas y organización de datos
-   Importación y manejo de datos
-   Manipulación de datos con tidyverse
-   Introducción a pruebas estadísticas básicas
-   Ciencia reproducible (Introducción a R Markdown y Quarto)

## Zona de descarga {.smaller}

Aquí podrás descargar un documento .pdf del contenido de este curso.
